version: '3.7'

networks:
  web_app:
    driver: bridge
    name: web_app_network

services:
  db:
    image: mysql:8
    container_name: mysqldb
    networks:
      - web_app
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=service_booking_system_db
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s  # 健康檢查命令的超時時間
      interval: 5s # 檢查間隔時間
      retries: 10   # 如果健康檢查命令失敗，Docker 將進行的重試次數，
    volumes:
      - ./db_data:/var/lib/mysql
      - ./database/backup.sql:/docker-entrypoint-initdb.d/backup.sql

  app:
    image: springboot
    container_name: spring-boot-app
    environment:
      - MYSQL_HOST=mysqldb   # same as container-name of db
      - MYSQL_PORT=3306
    networks:
      - web_app
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
volumes:
  db_data: