version: '3.7'
services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
    image: book_service_frontend
    ports:
      - "80:80"
    networks:
      - frontend_network

networks:
  frontend_network:
    driver: bridge